packages:
  - 'packages/*'
  - 'apps/*'
  - 'workers/*'

minimumReleaseAgeExclude:
  - '@knight-lab/timeline-ng-core'
  - '@knight-lab/timeline-ng'

allowBuilds:
  core-js: true
  esbuild: true
  sharp: false
  workerd: true
