/*
 * Font pairings carried forward from TimelineJS 3.
 *
 * GENERATED by scripts/fonts/generate-pairings.mjs — do not edit by hand.
 * Source: https://cdn.knightlab.com/libs/timeline3/latest/css/fonts (extracted 2026-08-24)
 *
 * A pairing is a set of --tl-* token values, nothing more. It does not load
 * anything: `webfonts` names the families a host must serve for the pairing to
 * render as designed, and `scripts` records which writing systems both of its
 * faces actually cover.
 *
 * That `scripts` list is the important one for an international audience. Most
 * of these families are Latin-and-maybe-Cyrillic only; a timeline written in a
 * script outside the list still renders, but from the stack's generic fallback
 * rather than the chosen face, per character. A pairing with no webfonts at all
 * ('system') inherits the reader's OS coverage, which is why it is the safe
 * default rather than the boring one.
 */

export interface FontPairing {
  id: FontPairingId;
  /** Human-readable "Heading + Body". */
  label: string;
  heading: string;
  body: string;
  /** Writing systems both faces cover; ['system'] means OS fonts, so all. */
  scripts: string[];
  /** Families the host must serve; empty for system-font pairings. */
  webfonts: string[];
  /** --tl-* values to apply. */
  tokens: Record<string, string>;
}

/**
 * Every id TLSettings.fontPairing accepts. This is deliberately a superset of
 * the ids in FONT_PAIRINGS: what a record may *name* includes aliases, while
 * what the UI *offers* does not. See PAIRING_ALIASES.
 */
export type FontPairingId =
  | 'georgia-helvetica'
  | 'pt'
  | 'ubuntu'
  | 'oldstandard'
  | 'abril-droidsans'
  | 'amatic-andika'
  | 'bevan-pontanosans'
  | 'bitter-raleway'
  | 'clicker-garamond'
  | 'dancing-ledger'
  | 'fjalla-average'
  | 'lustria-lato'
  | 'medula-lato'
  | 'opensans-gentiumbook'
  | 'playfair'
  | 'playfair-faunaone'
  | 'roboto-megrim'
  | 'rufina-sintony'
  | 'unicaone-vollkorn'
  | 'default';

export const FONT_PAIRINGS: FontPairing[] = [
  {
    "id": "georgia-helvetica",
    "label": "Georgia + Helvetica Neue",
    "heading": "Georgia",
    "body": "Helvetica Neue",
    "scripts": [
      "system"
    ],
    "webfonts": [],
    "tokens": {
      "--tl-font-heading": "Georgia, Times, serif",
      "--tl-font-body": "'Helvetica Neue', Helvetica, Arial, 'MS Trebuchet', sans-serif",
      "--tl-body-size": "1.0625rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.625rem)",
      "--tl-headline-weight": "800"
    }
  },
  {
    "id": "pt",
    "label": "PT Sans Narrow + PT Serif",
    "heading": "PT Sans Narrow",
    "body": "PT Serif",
    "scripts": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext"
    ],
    "webfonts": [
      "PT Serif",
      "PT Sans Narrow"
    ],
    "tokens": {
      "--tl-font-heading": "'PT Sans Narrow', sans-serif",
      "--tl-font-body": "'PT Serif', serif",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)",
      "--tl-headline-transform": "uppercase"
    }
  },
  {
    "id": "ubuntu",
    "label": "Ubuntu + Ubuntu",
    "heading": "Ubuntu",
    "body": "Ubuntu",
    "scripts": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "greek-ext",
      "latin",
      "latin-ext"
    ],
    "webfonts": [
      "Ubuntu"
    ],
    "tokens": {
      "--tl-font-heading": "Ubuntu, 'Helvetica Neue', Helvetica, Arial, 'MS Trebuchet', sans-serif",
      "--tl-font-body": "Ubuntu, 'Helvetica Neue', Helvetica, Arial, 'MS Trebuchet', sans-serif",
      "--tl-body-size": "1.0625rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.5rem)",
      "--tl-headline-weight": "500"
    }
  },
  {
    "id": "oldstandard",
    "label": "Old Standard TT + Old Standard TT",
    "heading": "Old Standard TT",
    "body": "Old Standard TT",
    "scripts": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "webfonts": [
      "Old Standard TT"
    ],
    "tokens": {
      "--tl-font-heading": "'Old Standard TT', serif",
      "--tl-font-body": "'Old Standard TT', serif",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)",
      "--tl-headline-weight": "400",
      "--tl-headline-transform": "uppercase"
    }
  },
  {
    "id": "abril-droidsans",
    "label": "Abril Fatface + Noto Sans",
    "heading": "Abril Fatface",
    "body": "Noto Sans",
    "scripts": [
      "latin",
      "latin-ext"
    ],
    "webfonts": [
      "Noto Sans",
      "Abril Fatface"
    ],
    "tokens": {
      "--tl-font-heading": "'Abril Fatface', cursive",
      "--tl-font-body": "'Noto Sans', sans-serif",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)"
    }
  },
  {
    "id": "amatic-andika",
    "label": "Amatic SC + Andika",
    "heading": "Amatic SC",
    "body": "Andika",
    "scripts": [
      "cyrillic",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "webfonts": [
      "Andika",
      "Amatic SC"
    ],
    "tokens": {
      "--tl-font-heading": "'Amatic SC', cursive",
      "--tl-font-body": "Andika, sans-serif",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 4rem)"
    }
  },
  {
    "id": "bevan-pontanosans",
    "label": "Bevan + Pontano Sans",
    "heading": "Bevan",
    "body": "Pontano Sans",
    "scripts": [
      "latin",
      "latin-ext"
    ],
    "webfonts": [
      "Pontano Sans",
      "Bevan"
    ],
    "tokens": {
      "--tl-font-heading": "Bevan, cursive",
      "--tl-font-body": "'Pontano Sans', sans-serif",
      "--tl-body-size": "1.0625rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.375rem)",
      "--tl-headline-weight": "400"
    }
  },
  {
    "id": "bitter-raleway",
    "label": "Bitter + Raleway",
    "heading": "Bitter",
    "body": "Raleway",
    "scripts": [
      "cyrillic",
      "cyrillic-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "webfonts": [
      "Raleway",
      "Bitter"
    ],
    "tokens": {
      "--tl-font-heading": "Bitter, serif",
      "--tl-font-body": "Raleway, sans-serif",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)"
    }
  },
  {
    "id": "clicker-garamond",
    "label": "Clicker Script + EB Garamond",
    "heading": "Clicker Script",
    "body": "EB Garamond",
    "scripts": [
      "latin",
      "latin-ext"
    ],
    "webfonts": [
      "EB Garamond",
      "Clicker Script"
    ],
    "tokens": {
      "--tl-font-heading": "'Clicker Script', cursive",
      "--tl-font-body": "'EB Garamond', serif",
      "--tl-body-size": "1.125rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 3.625rem)",
      "--tl-headline-weight": "400"
    }
  },
  {
    "id": "dancing-ledger",
    "label": "Dancing Script + Ledger",
    "heading": "Dancing Script",
    "body": "Ledger",
    "scripts": [
      "latin",
      "latin-ext"
    ],
    "webfonts": [
      "Ledger",
      "Dancing Script"
    ],
    "tokens": {
      "--tl-font-heading": "'Dancing Script', cursive",
      "--tl-font-body": "Ledger, serif",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 3.625rem)"
    }
  },
  {
    "id": "fjalla-average",
    "label": "Fjalla One + Average Sans",
    "heading": "Fjalla One",
    "body": "Average Sans",
    "scripts": [
      "latin",
      "latin-ext"
    ],
    "webfonts": [
      "Average Sans",
      "Fjalla One"
    ],
    "tokens": {
      "--tl-font-heading": "'Fjalla One', sans-serif",
      "--tl-font-body": "'Average Sans', sans-serif",
      "--tl-body-size": "1.0625rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)",
      "--tl-headline-weight": "400"
    }
  },
  {
    "id": "lustria-lato",
    "label": "Lustria + Lato",
    "heading": "Lustria",
    "body": "Lato",
    "scripts": [
      "latin"
    ],
    "webfonts": [
      "Lato",
      "Lustria"
    ],
    "tokens": {
      "--tl-font-heading": "Lustria, serif",
      "--tl-font-body": "Lato, sans-serif",
      "--tl-body-size": "1.0625rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)",
      "--tl-headline-weight": "400"
    }
  },
  {
    "id": "medula-lato",
    "label": "Medula One + Lato",
    "heading": "Medula One",
    "body": "Lato",
    "scripts": [
      "latin"
    ],
    "webfonts": [
      "Lato",
      "Medula One"
    ],
    "tokens": {
      "--tl-font-heading": "'Medula One', cursive",
      "--tl-font-body": "Lato, sans-serif",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 3.625rem)"
    }
  },
  {
    "id": "opensans-gentiumbook",
    "label": "Open Sans + Gentium Book Plus",
    "heading": "Open Sans",
    "body": "Gentium Book Plus",
    "scripts": [
      "cyrillic",
      "cyrillic-ext",
      "greek",
      "greek-ext",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "webfonts": [
      "Gentium Book Plus",
      "Open Sans"
    ],
    "tokens": {
      "--tl-font-heading": "'Open Sans', sans-serif",
      "--tl-font-body": "'Gentium Book Plus', serif",
      "--tl-body-size": "1.0625rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.5rem)",
      "--tl-headline-weight": "800"
    }
  },
  {
    "id": "playfair",
    "label": "Playfair Display SC + Playfair Display",
    "heading": "Playfair Display SC",
    "body": "Playfair Display",
    "scripts": [
      "cyrillic",
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "webfonts": [
      "Playfair Display",
      "Playfair Display SC"
    ],
    "tokens": {
      "--tl-font-heading": "'Playfair Display SC', serif",
      "--tl-font-body": "'Playfair Display', serif",
      "--tl-body-size": "1.0625rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)",
      "--tl-headline-weight": "400"
    }
  },
  {
    "id": "playfair-faunaone",
    "label": "Playfair Display + Fauna One",
    "heading": "Playfair Display",
    "body": "Fauna One",
    "scripts": [
      "latin",
      "latin-ext"
    ],
    "webfonts": [
      "Fauna One",
      "Playfair Display"
    ],
    "tokens": {
      "--tl-font-heading": "'Playfair Display', Georgia, serif",
      "--tl-font-body": "'Fauna One', serif",
      "--tl-body-size": "1.0625rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)",
      "--tl-headline-weight": "400",
      "--tl-headline-transform": "uppercase"
    }
  },
  {
    "id": "roboto-megrim",
    "label": "Megrim + Roboto Slab",
    "heading": "Megrim",
    "body": "Roboto Slab",
    "scripts": [
      "latin",
      "latin-ext"
    ],
    "webfonts": [
      "Roboto Slab",
      "Megrim"
    ],
    "tokens": {
      "--tl-font-heading": "Megrim, 'Helvetica Neue', Helvetica, Arial, 'MS Trebuchet', sans-serif",
      "--tl-font-body": "'Roboto Slab', Georgia, serif",
      "--tl-body-size": "1.0625rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)",
      "--tl-headline-weight": "400"
    }
  },
  {
    "id": "rufina-sintony",
    "label": "Rufina + Sintony",
    "heading": "Rufina",
    "body": "Sintony",
    "scripts": [
      "latin",
      "latin-ext"
    ],
    "webfonts": [
      "Sintony",
      "Rufina"
    ],
    "tokens": {
      "--tl-font-heading": "Rufina, serif",
      "--tl-font-body": "Sintony, sans-serif",
      "--tl-body-size": "0.9375rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)"
    }
  },
  {
    "id": "unicaone-vollkorn",
    "label": "Unica One + Vollkorn",
    "heading": "Unica One",
    "body": "Vollkorn",
    "scripts": [
      "latin",
      "latin-ext",
      "vietnamese"
    ],
    "webfonts": [
      "Vollkorn",
      "Unica One"
    ],
    "tokens": {
      "--tl-font-heading": "'Unica One', 'Helvetica Neue', Helvetica, Arial, 'MS Trebuchet', sans-serif",
      "--tl-font-body": "Vollkorn, Georgia, serif",
      "--tl-body-size": "1.0625rem",
      "--tl-headline-size": "clamp(1.2rem, 3cqi, 2.875rem)",
      "--tl-headline-weight": "400",
      "--tl-headline-transform": "uppercase"
    }
  }
];

export const DEFAULT_PAIRING: FontPairingId = 'georgia-helvetica';

/**
 * Ids that resolve to another pairing. TimelineJS 3 shipped `default` as a
 * duplicate of `pt` — the same two faces under a second name — so records
 * naming it still resolve, but it is not offered as a separate choice.
 */
export const PAIRING_ALIASES: Record<string, FontPairingId> = { default: 'pt' };

export function getPairing(id: string | undefined): FontPairing | undefined {
  if (!id) return undefined;
  const resolved = PAIRING_ALIASES[id] ?? id;
  return FONT_PAIRINGS.find(p => p.id === resolved);
}

/**
 * Whether a pairing's faces cover `language`'s script. Used to warn an author
 * that their chosen pairing will fall back rather than render as shown.
 */
export function coversLanguage(pairing: FontPairing, language: string): boolean {
  if (pairing.scripts.includes('system')) return true;
  const base = language.toLowerCase().split('-')[0];
  /*
   * Languages whose script is not Latin. Anything absent is assumed Latin —
   * a safe default given the long tail is overwhelmingly Latin-script
   * European languages, and a wrong guess here only costs a spurious warning.
   * Scripts no Google Latin/Cyrillic family covers (CJK, Arabic, Hebrew,
   * Thai, Indic) will never appear in a pairing's list, so they correctly
   * report as uncovered.
   */
  const SCRIPT_BY_LANG: Record<string, string> = {
    ru: 'cyrillic', uk: 'cyrillic', bg: 'cyrillic', sr: 'cyrillic', mk: 'cyrillic',
    be: 'cyrillic', kk: 'cyrillic', mn: 'cyrillic',
    el: 'greek', vi: 'vietnamese',
    hi: 'devanagari', mr: 'devanagari', ne: 'devanagari',
    ja: 'japanese', zh: 'chinese', ko: 'korean',
    ar: 'arabic', fa: 'arabic', ur: 'arabic',
    he: 'hebrew', th: 'thai', bn: 'bengali', ta: 'tamil',
    ka: 'georgian', hy: 'armenian', am: 'ethiopic', km: 'khmer', my: 'myanmar',
  };
  const needed = SCRIPT_BY_LANG[base] ?? 'latin';
  return pairing.scripts.includes(needed);
}
