#!/usr/bin/env node
/**
 * Download every unicode-range slice named in manifest.json as woff2, and emit
 * one self-hosted stylesheet per pairing.
 *
 * Self-hosting rather than hotlinking gstatic, for three reasons: it keeps
 * viewers' IP addresses from reaching a third party (hotlinked Google Fonts
 * were found to breach GDPR by LG München I in 2022), it sidesteps any host
 * page's font-src policy, and it costs nothing — the shared-cache argument for
 * using Google's CDN died in 2020 when browsers partitioned HTTP cache by
 * top-level site. Google Fonts are OFL/Apache licensed, so redistribution is
 * explicitly permitted.
 *
 * Every slice is kept. The generated @font-face rules carry their unicode-range
 * unchanged, so a browser downloads only the scripts a given timeline's text
 * actually uses — a Cyrillic timeline pulls the Cyrillic slice and never
 * touches Latin.
 *
 *   node scripts/fonts/fetch-fonts.mjs [outDir]
 *
 * Default outDir is packages/embed/public/fonts. Output is gitignored: it is
 * reproducible from the manifest, and binaries do not belong in the tree.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../..');
const OUT = resolve(REPO, process.argv[2] ?? 'packages/embed/public/fonts');

const manifest = JSON.parse(readFileSync(resolve(HERE, 'manifest.json'), 'utf8'));

const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const fileFor = (family, f) =>
  `${slug(family)}-${f.weight}${f.style === 'italic' ? 'i' : ''}-${f.script}.woff2`;

mkdirSync(OUT, { recursive: true });

let fetched = 0, cached = 0, bytes = 0;

for (const [id, set] of Object.entries(manifest.sets)) {
  const faces = [];

  for (const [family, resolved] of Object.entries(set.families)) {
    for (const f of resolved.faces) {
      const name = fileFor(family, f);
      const path = join(OUT, name);

      if (existsSync(path)) {
        cached++;
        bytes += statSync(path).size;
      } else {
        const res = await fetch(f.url);
        if (!res.ok) {
          console.warn(`  ${id}: ${name} — HTTP ${res.status}`);
          continue;
        }
        const buf = Buffer.from(await res.arrayBuffer());
        writeFileSync(path, buf);
        fetched++;
        bytes += buf.length;
      }

      faces.push(
        `@font-face {\n` +
          `  font-family: '${family}';\n` +
          `  font-style: ${f.style};\n` +
          `  font-weight: ${f.weight};\n` +
          `  font-display: swap;\n` +
          `  src: url(./${name}) format('woff2');\n` +
          (f.unicodeRange ? `  unicode-range: ${f.unicodeRange};\n` : '') +
          `}`,
      );
    }
  }

  if (!faces.length) continue;   // system-font pairing — no stylesheet needed

  writeFileSync(
    join(OUT, `${id}.css`),
    `/* ${id} — generated by scripts/fonts/fetch-fonts.mjs, do not edit. */\n` +
      `/* Slices carry their unicode-range: the browser fetches only the\n` +
      `   scripts this timeline's text actually needs. */\n\n` +
      faces.join('\n\n') +
      '\n',
  );
}

console.log(`${OUT}`);
console.log(`  ${fetched} downloaded, ${cached} already present`);
console.log(`  ${(bytes / 1024 / 1024).toFixed(1)} MB at rest`);
