#!/usr/bin/env node
/**
 * Download every unicode-range slice named in manifest.json as woff2, and emit
 * one self-hosted stylesheet per pairing.
 *
 * Self-hosting rather than hotlinking gstatic, for three reasons: it keeps
 * viewers' IP addresses from reaching a third party (hotlinked Google Fonts
 * were found to breach GDPR by LG München I in 2022), it sidesteps any host
 * page's font-src policy, and it costs nothing — the shared-cache argument for
 * using Google's CDN died in 2020 when browsers partitioned HTTP cache by
 * top-level site. Google Fonts are OFL/Apache licensed, so redistribution is
 * explicitly permitted.
 *
 * Every slice is kept. The generated @font-face rules carry their unicode-range
 * unchanged, so a browser downloads only the scripts a given timeline's text
 * actually uses — a Cyrillic timeline pulls the Cyrillic slice and never
 * touches Latin.
 *
 * Every file is checked against the SHA-256 recorded in the manifest. That is
 * what makes the mirror recoverable: without it a corrupted or truncated file
 * is indistinguishable from a good one, and an upstream that has quietly
 * changed looks the same as one that has not. A mismatch is an error, not a
 * warning — a font that is not the font we verified should stop the build
 * rather than ship.
 *
 *   node scripts/fonts/fetch-fonts.mjs [outDir]
 *
 * Default outDir is packages/embed/public/fonts. Output is gitignored: it is
 * reproducible from the manifest, and binaries do not belong in the tree.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../..');
const OUT = resolve(REPO, process.argv[2] ?? 'packages/embed/public/fonts');

const manifest = JSON.parse(readFileSync(resolve(HERE, 'manifest.json'), 'utf8'));

const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const sha256 = buf => createHash('sha256').update(buf).digest('hex');
const fileFor = (family, f) =>
  `${slug(family)}-${f.weight}${f.style === 'italic' ? 'i' : ''}-${f.script}.woff2`;

mkdirSync(OUT, { recursive: true });

let fetched = 0, cached = 0, bytes = 0, pinned = 0;
const corrupt = [];
const missing = [];

for (const [id, set] of Object.entries(manifest.sets)) {
  const faces = [];

  for (const [family, resolved] of Object.entries(set.families)) {
    for (const f of resolved.faces) {
      const name = fileFor(family, f);
      const path = join(OUT, name);

      let buf;
      if (existsSync(path)) {
        /* Verify what is on disk rather than trusting its presence. */
        buf = readFileSync(path);
        cached++;
      } else {
        const res = await fetch(f.url);
        if (!res.ok) {
          missing.push(`${name} — HTTP ${res.status} from ${f.url}`);
          continue;
        }
        buf = Buffer.from(await res.arrayBuffer());
        writeFileSync(path, buf);
        fetched++;
      }
      bytes += buf.length;

      const digest = sha256(buf);
      if (!f.sha256) {
        /* First sight of these bytes — pin them. */
        f.sha256 = digest;
        pinned++;
      } else if (digest !== f.sha256) {
        /* Upstream URLs are versioned (/s/ptsans/v18/…), so different bytes at
           a pinned URL means the file was republished — not something to accept
           silently just because the download succeeded. */
        corrupt.push(`${name} — expected ${f.sha256.slice(0, 12)}…, got ${digest.slice(0, 12)}…`);
      }

      faces.push(
        `@font-face {\n` +
          `  font-family: '${family}';\n` +
          `  font-style: ${f.style};\n` +
          `  font-weight: ${f.weight};\n` +
          `  font-display: swap;\n` +
          `  src: url(./${name}) format('woff2');\n` +
          (f.unicodeRange ? `  unicode-range: ${f.unicodeRange};\n` : '') +
          `}`,
      );
    }
  }

  if (!faces.length) continue;   // system-font pairing — no stylesheet needed

  writeFileSync(
    join(OUT, `${id}.css`),
    `/* ${id} — generated by scripts/fonts/fetch-fonts.mjs, do not edit. */\n` +
      `/* Slices carry their unicode-range: the browser fetches only the\n` +
      `   scripts this timeline's text actually needs. */\n\n` +
      faces.join('\n\n') +
      '\n',
  );
}

console.log(`${OUT}`);
console.log(`  ${fetched} downloaded, ${cached} already present`);
console.log(`  ${(bytes / 1024 / 1024).toFixed(1)} MB at rest`);

if (pinned) {
  writeFileSync(resolve(HERE, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
  console.log(`  ${pinned} newly pinned in manifest.json`);
} else if (!corrupt.length) {
  console.log(`  all ${cached + fetched} verified against manifest.json`);
}

if (missing.length) {
  console.error(`\n${missing.length} file(s) could not be fetched:`);
  for (const m of missing) console.error(`  ${m}`);
}
if (corrupt.length) {
  console.error(`\n${corrupt.length} file(s) failed their SHA-256 check:`);
  for (const c of corrupt) console.error(`  ${c}`);
  console.error(`\nDelete the offending file(s) to re-fetch, or if upstream has`);
  console.error(`legitimately republished, re-run 'pnpm fonts:extract' to re-pin.`);
}
if (missing.length || corrupt.length) process.exit(1);
